### ISSUE TITLE
E-Mail Template - Customised for target 

### ISSUE THREAD

**Issue by Armellys** [certsocietegenerale/swordphish-awareness#12]
Hi,

I was wondering if there is any possibility to send custom e-mail according to the target, like something with there names or e-mail adress directly in the e-mail body. Like : 

Hi [Name],

We sent you an e-mail to [e-mail adress] because someone try to connect to your account.
If it's not you, quickly connect to www.phishing.com to prove your identity !

Thx.

**Comment by Heat-Miser** [comment]
Hello,

this feature has been asked a few times, I'm working on it.

I'll release this feature as soon as I'll have enough time to test it correctly.

**Comment by Heat-Miser** [comment]
I've just added the feature, don't hesitate to test it.

It's based on targets tags, you can insert tag value in the mail by using the following syntax in the template($tag_name$). It'll be automatically replaced by tag_value.
