### ISSUE TITLE
pulling is unavailable?

### ISSUE THREAD

**Issue by y0d4a** [certsocietegenerale/swordphish-awareness#19]
Pulling swordphish-worker (swordphish:)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

or

Pulling swordphish-worker (swordphish:)...
ERROR: pull access denied for swordphish, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

?

**Comment by Heat-Miser** [comment]
Hello,

I don't understand this issue, can you please give more details about what you're trying to do ?

thanks

**Comment by y0d4a** [comment]
just fallow installing instruction.
Cloned repo, enter in docker folder, tried to pull docker image and he said that i don't have permission to pull?

**Comment by Heat-Miser** [comment]
Oh I see.

You’re not supposed to pull, the images are not published. 

Do a docker-compose build then docker-compose up to start the app.

**Comment by Heat-Miser** [comment]
Hello,

were you able to start the docker infra ?

Can I close this issue ?

Thanks

**Comment by y0d4a** [comment]
ah i forgot on this :(
just tried and get it up and running :)
thank you!

**Comment by Heat-Miser** [comment]
Great news ! Thanks

**Comment by vladimir-monari** [comment]
Hello,

I just tried to build it and run compose-up. It work well. I think You can close this issue.

Many Thanks !
