### ISSUE TITLE
docker image? :)

### ISSUE THREAD

**Issue by y0d4a** [certsocietegenerale/swordphish-awareness#2]
hello, first thank you for make this public! 
second, is possible to make it under docker image? :)

tnx.

**Comment by certsocietegenerale** [comment]
Hello,

it's not in the roadmap but we'll think about it !

Feel free to contribute 🙂

**Comment by Heat-Miser** [comment]
Hello,

A docker-compose script has been added to the repo. Feel free to test it :)

It's for testing purpose only. I'll try to make something more "production" compliant in the future.
