### ISSUE TITLE
Installation dependecies

### ISSUE THREAD

**Issue by dyneko** [certsocietegenerale/swordphish-awareness#4]
Hi,

I found error in these lines when I did the install : 
#change the git link
$swordphish>git clone https://github.com/certsocietegenerale/swordphish-awareness.git

#Change the execution command
$swordphish>mkvirtualenv --python=python3 -a /home/swordphish/swordphish/ swordphish

**Comment by certsocietegenerale** [comment]
Fixed thanks a heap.
