### ISSUE TITLE
Mail vars

### ISSUE THREAD

**Issue by dyneko** [certsocietegenerale/swordphish-awareness#5]
Hi,

How can we use the mail variables for instance name, what is the synthaxe ?

As well, which html editor you to manage the template, it's a little buggy, is it possible to update it ?

**Comment by certsocietegenerale** [comment]
Hello, 

Not sure to understand the question about the mail variables, do you want to use tags in mail templates ? This feature is not implemented yet but it's in the roadmap (without any date yet).

Regarding the editor, can you specify the problems you're encountering ?

Thanks

**Comment by dyneko** [comment]
Yeah I want to use tag, like %name%

The editor can't import picture and you modify, it changes the page organization, that's why is it possible to update to last version of editor ? how ?

**Comment by Heat-Miser** [comment]
Okay thanks for clarifying.

Regarding the tags, it will be implemented in the future. I keep this issue opened to track it.

Regarding the editor, how do you import images ? The editor successfully imports images and store them in the templates directly encoded in base64 (to avoid managing uploads and template forging).

I updated to one the last version available just before publishing the tool (5.6.1).

**Comment by Heat-Miser** [comment]
I'll consider providing a dump of template examples, that's a good idea.

Regarding the fact Outllook put your mail in the junk, this is related to the way you configured your mail server not Swordphish.

Lucy is a paying solution with full infrastructure provided, I provide Swordphish for free, but you have to setup your own infrastructure and manage the way the mails are delivered. As Swordphish is not used to do redteam missions or something like that you can consider whitelisting your server for having to manage the antispam problems.

**Comment by Heat-Miser** [comment]
I've just added the feature, don't hesitate to test it.

It's based on targets tags, you can insert tag value in the mail by using the following syntax in the template($tag_name$). It'll be automatically replaced by tag_value.
