### ISSUE TITLE
Documentation update required

### ISSUE THREAD

**Issue by Sh4dw0lf** [certsocietegenerale/swordphish-awareness#6]
Hello

There is an error within the documentation. It says : 

> Switch to newly created user and git-clone Swordphish repository:
> ```
> #>su - swordphish
> $swordphish>git clone https://github.com/certsocietegenerale/swordphish.git
> ```
> 

But it appears the **-awareness** is missing within the link. Thus the proprer link is : 
`$swordphish>git clone https://github.com/certsocietegenerale/swordphish-awareness.git`

**Comment by Sh4dw0lf** [comment]
Same comment on the following instruction
`$swordphish>mkvirtualenv -p python3 -a /home/swordphish/swordphish/ swordphish`

**Comment by Heat-Miser** [comment]
Hello, 

This should have been fixed following this issue

https://github.com/certsocietegenerale/swordphish-awareness/issues/4

Regards,
