### ISSUE TITLE
Error in Symbolik Link ?

### ISSUE THREAD

**Issue by Sh4dw0lf** [certsocietegenerale/swordphish-awareness#7]
Hello,

Isn't there a problem within the Symbolic links ?

`#>ln -s /etc/nginx/sites-enabled/swordphish.conf /etc/nginx/sites-available/swordphish.conf

#>ln -s /etc/nginx/sites-enabled/swordphish_phishing_domains.conf /etc/nginx/sites-available/swordphish_phishing_domains.conf`

Shouldn't it be the opposite ? You create the symbolic links on sites-enabled and not on sites-available.

**Comment by Heat-Miser** [comment]
Hello,

I mistakenly switched dest and source indeed, thanks for notifying me this error. 

Corrected
